/*
 * T+ file was generated by the Gradle 'init' task.
 */
package Client;

import java.awt.Graphics;
import java.awt.image.BufferStrategy;
import java.net.URI;
import java.net.URISyntaxException;

import org.json.JSONObject;

import Client.game.Game;
import Client.game.engine.WindowManager;
import Client.server.ServerConnection;

public class App{
  

	private static final String serverUri = "ws://localhost:8888";
	
	
	private Game game;
	
	
	private ServerConnection connection;
	
	public App(boolean offline) throws URISyntaxException {
	    game = new Game(this,offline);
	    if(!offline) {
		connection= new ServerConnection(new URI(serverUri),this);
		connection.connect();
	    }
	    
		
		
	}
	
	
	
	
	
	public boolean send(JSONObject object) {
		if(connection.isOpen()) {
			connection.send(object.toString());
			return true;
		}else {
			Logger.info("Cannot send object because connection is not open!");
			return false;
		}
		
	}
	
	public void onMessage(JSONObject object) {
	    game.onMessage(object);
	}
	
	

	public static void main(String[] args) throws URISyntaxException {
	    new App(false);
    }
    
	
	
}
