/*
 * T+ file was generated by the Gradle 'init' task.
 */
package Client;

import java.awt.Graphics;
import java.awt.image.BufferStrategy;
import java.net.URI;
import java.net.URISyntaxException;

import org.json.JSONObject;

import Client.game.engine.WindowManager;
import Client.server.ServerConnection;

public class App{
  

	private static final String serverUri = "ws://localhost:8888";
	
	
	private WindowManager window;
	
	private Thread thread;
	
	
	private ServerConnection connection;
	
	public App() throws URISyntaxException {
//		connection= new ServerConnection(new URI(serverUri));
//		connection.connect();
		
		window = new WindowManager();
		thread = new Thread(window);
		thread.start();
	}
	
	
	
	
	
	public void send(JSONObject object) {
		if(connection.isOpen()) {
			connection.send(object.toString());
		}else {
			Logger.info("Cannot send object because connection is not open!");
		}
		
	}
	

	
	

	public static void main(String[] args) throws URISyntaxException {
       new App();
    }
    
	
	
}
