/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Server;

import java.net.InetSocketAddress;

import Server.net.Server;

public class App {
    
	private static final int port = 8888;

	public App() {
		Server server = new Server(new InetSocketAddress("localhost",port));
		server.run();
		
	}
	
	
	
	
    public static void main(String[] args) {
        new App();
    }
}
